apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
  namespace: hello-world-namespace
spec:
  selector:
    app: hello-world
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer