apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
  namespace: hello-world-namespace
spec:
  selector:
    app: hello-world
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080